# Generated by Django 5.1.3 on 2024-11-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chamado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("whatsapp", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("departamento", models.CharField(max_length=100)),
                (
                    "tipo_problema",
                    models.CharField(
                        choices=[
                            ("Hardware", "Hardware"),
                            ("Software", "Software"),
                            ("Rede", "Rede"),
                            ("Acesso", "Acesso"),
                            ("Outro", "Outro"),
                        ],
                        max_length=50,
                    ),
                ),
                ("descricao_problema", models.TextField()),
                (
                    "urgencia",
                    models.CharField(
                        choices=[
                            ("Baixa", "Baixa"),
                            ("Média", "Média"),
                            ("Alta", "Alta"),
                            ("Crítica", "Crítica"),
                        ],
                        default="Baixa",
                        max_length=10,
                    ),
                ),
                ("data_solicitacao", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
