# Generated by Django 5.1.3 on 2024-11-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chamados", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chamado",
            name="numero_anydesk",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="chamado",
            name="ramal",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="chamado",
            name="departamento",
            field=models.CharField(
                choices=[
                    ("Tecnologia", "Tecnologia"),
                    ("Recepção", "Recepção"),
                    ("Diretoria", "Diretoria"),
                    ("Departamento Pessoal", "Departamento Pessoal"),
                    ("Financeiro", "Financeiro"),
                    ("Contabilidade", "Contabilidade"),
                    ("Contratos", "Contratos"),
                    ("Consórcios", "Consórcios"),
                    ("Controladoria", "Controladoria"),
                    ("Jurídico", "Jurídico"),
                    ("Licitação", "Licitação"),
                    ("Segurança do Trabalho", "Segurança do Trabalho"),
                    ("Obras", "Obras"),
                    ("Equipes", "Equipes"),
                ],
                max_length=50,
            ),
        ),
    ]
