# Generated by Django 5.1.3 on 2024-11-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chamados", "0003_chamado_sobrenome"),
    ]

    operations = [
        migrations.AddField(
            model_name="chamado",
            name="status",
            field=models.CharField(
                choices=[("Pendente", "Pendente"), ("Atendido", "Atendido")],
                default="Pendente",
                max_length=10,
            ),
        ),
    ]
