# Generated by Django 5.1.3 on 2024-11-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chamados", "0004_chamado_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chamado",
            name="tipo_problema",
            field=models.CharField(
                choices=[
                    (
                        "Problemas técnicos no computador",
                        "Problemas técnicos no computador",
                    ),
                    ("Computador quebrado", "Computador quebrado"),
                    (
                        "Problemas relacionados ao Protheus (TOTVS)",
                        "Problemas relacionados ao Protheus (TOTVS)",
                    ),
                    ("Perda de internet", "Perda de internet"),
                    ("Problemas de Rede", "Problemas de Rede"),
                    ("Erro em Sistema ou Software", "Erro em Sistema ou Software"),
                    ("Outro", "Outro"),
                ],
                max_length=50,
            ),
        ),
    ]
