# Generated by Django 5.1.3 on 2024-11-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chamados", "0005_alter_chamado_tipo_problema"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chamado",
            name="urgencia",
            field=models.CharField(
                choices=[
                    ("Nível diretoria", "Nível diretoria"),
                    ("É urgente", "É urgente"),
                    ("Posso esperar 30 minutos", "Posso esperar 30 minutos"),
                    ("Posso esperar 1 hora", "Posso esperar 1 hora"),
                    ("Posso esperar 3 horas", "Posso esperar 3 horas"),
                    ("Posso esperar 1 dia", "Posso esperar 1 dia"),
                    (
                        "Estou sem pressa, porém precisa ser resolvido",
                        "Estou sem pressa, porém precisa ser resolvido",
                    ),
                ],
                default="Estou sem pressa",
                max_length=50,
            ),
        ),
    ]
