# Generated by Django 5.1.3 on 2024-11-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chamados", "0006_alter_chamado_urgencia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chamado",
            name="urgencia",
            field=models.CharField(
                choices=[
                    ("Nível diretoria", "Nível diretoria"),
                    (
                        "Consigo trabalhar, porém o programa não funciona",
                        "Consigo trabalhar, porém o programa não funciona",
                    ),
                    (
                        "Não consigo trabalhar, nada funciona",
                        "Não consigo trabalhar, nada funciona",
                    ),
                    (
                        "Não consigo trabalhar, meu computador não funciona",
                        "Não consigo trabalhar, meu computador não funciona",
                    ),
                    (
                        "Consigo trabalhar, porém o computador trava muito",
                        "Consigo trabalhar, porém o computador trava muito",
                    ),
                    ("Consigo esperar algum tempo", "Consigo esperar algum tempo"),
                    ("Posso esperar 30 minutos", "Posso esperar 30 minutos"),
                    ("Posso esperar 1 hora", "Posso esperar 1 hora"),
                    ("Posso esperar 3 horas", "Posso esperar 3 horas"),
                    ("Posso esperar 1 dia", "Posso esperar 1 dia"),
                    (
                        "Estou sem pressa, porém precisa ser resolvido",
                        "Estou sem pressa, porém precisa ser resolvido",
                    ),
                    (
                        "Precisa ser resolvido até o final do dia",
                        "Precisa ser resolvido até o final do dia",
                    ),
                    (
                        "Precisa ser resolvido na próxima semana",
                        "Precisa ser resolvido na próxima semana",
                    ),
                ],
                default="Estou sem pressa",
                max_length=50,
            ),
        ),
    ]
