# Generated by Django 5.1.3 on 2024-11-25 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                ("quantidade", models.PositiveIntegerField()),
                (
                    "codigo_produto",
                    models.CharField(
                        default="DEFAULT_CODE", max_length=50, unique=True
                    ),
                ),
                (
                    "unidade",
                    models.CharField(
                        choices=[
                            ("Unidade", "Unidade"),
                            ("Pacote", "Pacote"),
                            ("Caixa", "Caixa"),
                            ("Rolo", "Rolo"),
                            ("Cartucho", "Cartucho"),
                            ("Resma", "Resma"),
                            ("Frasco", "Frasco"),
                            ("Tubo", "Tubo"),
                            ("Par", "Par"),
                            ("Bloco", "Bloco"),
                            ("Kit", "Kit"),
                            ("Bobina", "Bobina"),
                            ("Galão", "Galão"),
                            ("Barra", "Barra"),
                            ("Livro", "Livro"),
                            ("Carrete", "Carrete"),
                            ("Lata", "Lata"),
                            ("Peça", "Peça"),
                            ("Metro", "Metro"),
                        ],
                        default="Unidade",
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Solicitacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_completo", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("departamento", models.CharField(max_length=100)),
                ("data_solicitacao", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pendente", "Pendente"),
                            ("Aprovado", "Aprovado"),
                            ("Recusado", "Recusado"),
                        ],
                        default="Pendente",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SolicitacaoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade_solicitada", models.PositiveIntegerField()),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="estoque.material",
                    ),
                ),
                (
                    "solicitacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="estoque.solicitacao",
                    ),
                ),
            ],
        ),
    ]
