# Generated by Django 5.1.3 on 2024-11-25 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estoque", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SolicitacaoCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fornecedor", models.CharField(max_length=100)),
                ("data_solicitacao", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pendente", "Pendente"),
                            ("Aprovado", "Aprovado"),
                            ("Recusado", "Recusado"),
                        ],
                        default="Pendente",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SolicitacaoCompraItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade_comprada", models.PositiveIntegerField()),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="estoque.material",
                    ),
                ),
                (
                    "solicitacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="estoque.solicitacaocompra",
                    ),
                ),
            ],
        ),
    ]
