# Generated by Django 5.1.3 on 2024-11-25 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("estoque", "0002_solicitacaocompra_solicitacaocompraitem"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Solicitacao",
            new_name="RequisicaoDeMaterial",
        ),
        migrations.RenameModel(
            old_name="SolicitacaoItem",
            new_name="RequisicaoDeMaterialItem",
        ),
        migrations.RenameField(
            model_name="requisicaodematerial",
            old_name="data_solicitacao",
            new_name="data_requisicao",
        ),
        migrations.RenameField(
            model_name="requisicaodematerialitem",
            old_name="solicitacao",
            new_name="requisicao",
        ),
    ]
