# Generated by Django 5.1.3 on 2024-11-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estoque", "0007_material_fornecedor"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="codigo_produto",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
